import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import {
  ROOT,
  buildCoverage,
  buildFacilityRegister,
  buildModel,
  deriveProvinceCapacities,
  loadInputs,
  round,
  toCsv
} from "./lib/project.mjs";

const {project, benchmarks, geometry, inputHash} = loadInputs();
const provinces = deriveProvinceCapacities(project, geometry);
const {scenarios, resolveCapacity} = buildModel(project, provinces);
const facilityRegister = buildFacilityRegister(project, provinces);
const coverage = buildCoverage(project, benchmarks, facilityRegister, scenarios);
const generatedDir = resolve(ROOT, "generated");
const auditDir = resolve(ROOT, "audit");
mkdirSync(generatedDir, {recursive: true});
mkdirSync(auditDir, {recursive: true});

const outputMetadata = {
  schemaVersion: project.schemaVersion,
  inputSha256: inputHash,
  observationCutoff: project.metadata.observationCutoff,
  researchPublicationCutoff: project.metadata.researchPublicationCutoff,
  verificationDate: project.metadata.verificationDate,
  generationCommand: "npm run build"
};

const chartData = {
  metadata: outputMetadata,
  title: project.metadata.title,
  capacityStandard: project.capacityStandard,
  assumptions: project.assumptions,
  coverage,
  scenarios,
  sources: project.sources,
  exclusions: project.ledgerBlocks.map((block) => ({
    ...block,
    capacity: resolveCapacity(block.capacityRef),
    price: project.priceRecords.find((record) => record.id === block.priceRef)
  }))
};

writeFileSync(
  resolve(generatedDir, "chart-data.js"),
  `/* Generated by npm run build. Input SHA-256: ${inputHash} */\nwindow.COMPUTE_COST_DATA = ${JSON.stringify(chartData, null, 2)};\n`
);

const indexPath = resolve(ROOT, "index.html");
const indexHtml = readFileSync(indexPath, "utf8");
const versionedIndexHtml = indexHtml.replace(
  /generated\/chart-data\.js(?:\?v=[^"]+)?/g,
  `generated/chart-data.js?v=${inputHash.slice(0, 12)}`
);
if (versionedIndexHtml !== indexHtml) writeFileSync(indexPath, versionedIndexHtml);

const summary = {
  metadata: outputMetadata,
  capacityMetric: project.capacityStandard.metricId,
  provinceCount: provinces.length,
  nationalCapacityMw: round(provinces.reduce((sum, row) => sum + row.capacityMw, 0), 4),
  registeredCapacityMw: round(coverage.capacityRegister.registeredCapacityMw, 4),
  registeredRegionCount: coverage.capacityRegister.registeredRegionCount,
  indicativeGlobalCapacityCoveragePct: round(coverage.capacityRegister.globalCapacityCoveragePct, 2),
  sourceCounts: Object.fromEntries(
    [...new Set(project.sources.map((source) => source.verificationStatus))]
      .map((status) => [status, project.sources.filter((source) => source.verificationStatus === status).length])
  ),
  independentHumanReview: "pending",
  scenarios: scenarios.map((scenario) => ({
    id: scenario.id,
    blocks: scenario.blocks.length,
    totalCapacityMw: round(scenario.totalCapacityMw, 4),
    lowestCostLocation: scenario.blocks.at(0).location,
    highestCostLocation: scenario.blocks.at(-1).location
  })),
  priceCoverage: coverage.priceScenarios.map((scenario) => ({
    evidenceId: scenario.evidenceId,
    regionCount: scenario.regionsWithPrice,
    priceCoveredMw: round(scenario.priceCoveredMw, 4),
    registeredCapacityCoveragePct: round(scenario.registeredCapacityCoveragePct, 2),
    globalCapacityCoveragePct: round(scenario.globalCapacityCoveragePct, 2)
  })),
  largestCountryGaps: coverage.countryGaps.slice(0, 10).map((row) => ({
    country: row.country,
    missingCapacityMw: round(row.missingCapacityMw, 1),
    benchmarkScope: row.benchmarkScope
  }))
};
writeFileSync(resolve(generatedDir, "project-summary.json"), `${JSON.stringify(summary, null, 2)}\n`);

const capacityHeaders = [
  "input_sha256", "province", "abbreviation", "x0_px", "y0_px", "x1_px", "y1_px",
  "width_px", "height_px", "area_px2", "area_share", "standard_racks_estimate",
  "commissioned_design_it_power_mw", "observation_date", "source_ids"
];
writeFileSync(resolve(auditDir, "capacity-derivation.csv"), toCsv(capacityHeaders, provinces.map((row) => ({
  input_sha256: inputHash,
  province: row.province,
  abbreviation: row.abbreviation,
  x0_px: row.x0,
  y0_px: row.y0,
  x1_px: row.x1,
  y1_px: row.y1,
  width_px: row.widthPx,
  height_px: row.heightPx,
  area_px2: row.areaPx2,
  area_share: round(row.areaShare, 10),
  standard_racks_estimate: round(row.standardRacks, 2),
  commissioned_design_it_power_mw: round(row.capacityMw, 4),
  observation_date: row.observationDate,
  source_ids: row.sourceIds.join(";")
}))));

const scenarioHeaders = [
  "input_sha256", "evidence_scenario", "technology_scenario", "cost_order", "block_id",
  "location", "country", "commissioned_design_it_power_mw", "capacity_observation_date",
  "capacity_harmonization_grade", "price_evidence_class", "price_effective_date",
  "price_local_per_kwh", "price_currency", "price_usd_per_kwh", "technology",
  "technology_efficiency_multiplier", "cost_usd_per_1e19_dense_bf16_flops",
  "dense_bf16_flops_per_usd_e19", "source_ids"
];
writeFileSync(resolve(ROOT, "electricity-capacity-data.csv"), toCsv(scenarioHeaders,
  scenarios.flatMap((scenario) => scenario.blocks.map((block, index) => ({
    input_sha256: inputHash,
    evidence_scenario: scenario.evidenceId,
    technology_scenario: scenario.technologyId,
    cost_order: index + 1,
    block_id: block.id,
    location: block.location,
    country: block.country,
    commissioned_design_it_power_mw: round(block.capacityMw, 4),
    capacity_observation_date: block.capacityObservationDate,
    capacity_harmonization_grade: block.capacityHarmonizationGrade,
    price_evidence_class: block.priceEvidenceClass,
    price_effective_date: block.priceEffectiveDate,
    price_local_per_kwh: round(block.priceLocalPerKwh, 8),
    price_currency: block.priceCurrency,
    price_usd_per_kwh: round(block.priceUsdPerKwh, 8),
    technology: block.technology,
    technology_efficiency_multiplier: block.technologyMultiplier,
    cost_usd_per_1e19_dense_bf16_flops: round(block.costUsdPer1e19Flops, 8),
    dense_bf16_flops_per_usd_e19: round(block.denseBf16FlopsPerUsdE19, 8),
    source_ids: block.sourceIds.join(";")
  })))
));

const benchmarkHeaders = [
  "input_sha256", "record_id", "location", "region", "region_type", "country", "iso3",
  "record_type", "coverage_role", "status", "capacity_metric", "capacity_mw",
  "observation_date", "date_precision", "harmonization_grade", "coverage_note", "source_ids"
];
writeFileSync(resolve(ROOT, "global-benchmark-capacity-data.csv"), toCsv(benchmarkHeaders,
  facilityRegister.filter((record) => record.metricId === project.capacityStandard.metricId).map((record) => ({
    input_sha256: inputHash,
    record_id: record.id,
    location: record.location,
    region: record.region,
    region_type: record.regionType,
    country: record.country,
    iso3: record.iso3,
    record_type: record.recordType,
    coverage_role: record.coverageRole,
    status: record.status,
    capacity_metric: record.metricId,
    capacity_mw: round(record.capacityMw, 4),
    observation_date: record.observationDate,
    date_precision: record.datePrecision,
    harmonization_grade: record.harmonizationGrade,
    coverage_note: record.note,
    source_ids: record.sourceIds.join(";")
  }))
));

const facilityHeaders = [
  "input_sha256", "record_id", "location", "region", "region_type", "country", "iso3",
  "record_type", "coverage_role", "status", "capacity_metric", "capacity_mw",
  "observation_date", "date_precision", "harmonization_grade", "source_ids", "note"
];
writeFileSync(resolve(ROOT, "global-facility-register.csv"), toCsv(facilityHeaders,
  facilityRegister.map((record) => ({
    input_sha256: inputHash,
    record_id: record.id,
    location: record.location,
    region: record.region,
    region_type: record.regionType,
    country: record.country,
    iso3: record.iso3,
    record_type: record.recordType,
    coverage_role: record.coverageRole,
    status: record.status,
    capacity_metric: record.metricId,
    capacity_mw: round(record.capacityMw, 4),
    observation_date: record.observationDate,
    date_precision: record.datePrecision,
    harmonization_grade: record.harmonizationGrade,
    source_ids: record.sourceIds.join(";"),
    note: record.note
  }))
));

const coverageHeaders = [
  "input_sha256", "layer", "label", "capacity_mw", "registered_capacity_coverage_pct",
  "indicative_global_capacity_coverage_pct", "regions", "missing_price_capacity_mw", "denominator_note"
];
writeFileSync(resolve(ROOT, "coverage-summary.csv"), toCsv(coverageHeaders, [
  {
    input_sha256: inputHash,
    layer: "capacity_register",
    label: "Capacity registered independently of price availability",
    capacity_mw: round(coverage.capacityRegister.registeredCapacityMw, 4),
    registered_capacity_coverage_pct: 100,
    indicative_global_capacity_coverage_pct: round(coverage.capacityRegister.globalCapacityCoveragePct, 4),
    regions: coverage.capacityRegister.registeredRegionCount,
    missing_price_capacity_mw: "",
    denominator_note: `${benchmarks.globalBenchmark.capacityMw} MW indicative 2025 global benchmark`
  },
  ...coverage.priceScenarios.map((scenario) => ({
    input_sha256: inputHash,
    layer: scenario.evidenceId,
    label: scenario.label,
    capacity_mw: round(scenario.priceCoveredMw, 4),
    registered_capacity_coverage_pct: round(scenario.registeredCapacityCoveragePct, 4),
    indicative_global_capacity_coverage_pct: round(scenario.globalCapacityCoveragePct, 4),
    regions: scenario.regionsWithPrice,
    missing_price_capacity_mw: round(scenario.priceMissingMw, 4),
    denominator_note: "Price coverage uses registered capacity as its main denominator"
  }))
]));

const regionalCoverageHeaders = [
  "input_sha256", "layer", "layer_label", "country", "region", "capacity_mw",
  "share_of_layer_pct", "source_records"
];
writeFileSync(resolve(ROOT, "regional-coverage-breakdown.csv"), toCsv(regionalCoverageHeaders,
  coverage.regionBreakdowns.flatMap((layer) => layer.regions.map((region) => ({
    input_sha256: inputHash,
    layer: layer.layer,
    layer_label: layer.label,
    country: region.country,
    region: region.region,
    capacity_mw: round(region.capacityMw, 4),
    share_of_layer_pct: round(region.layerSharePct, 4),
    source_records: region.recordCount
  })))
));

const countryGapHeaders = [
  "input_sha256", "rank", "country", "iso3", "benchmark_capacity_mw",
  "registered_capacity_mw", "missing_capacity_mw", "benchmark_scope",
  "benchmark_status", "observation_date", "source_ids", "note"
];
writeFileSync(resolve(ROOT, "country-capacity-gaps.csv"), toCsv(countryGapHeaders,
  coverage.countryGaps.map((row, index) => ({
    input_sha256: inputHash,
    rank: index + 1,
    country: row.country,
    iso3: row.iso3,
    benchmark_capacity_mw: round(row.benchmarkCapacityMw, 4),
    registered_capacity_mw: round(row.registeredCapacityMw, 4),
    missing_capacity_mw: round(row.missingCapacityMw, 4),
    benchmark_scope: row.benchmarkScope,
    benchmark_status: row.benchmarkStatus,
    observation_date: row.observationDate,
    source_ids: row.sourceIds.join(";"),
    note: row.note
  }))
));

const technologyHeaders = [
  "input_sha256", "scenario_id", "scenario_title", "china_technology", "global_technology",
  "china_efficiency_multiplier", "global_efficiency_multiplier", "source_ids"
];
writeFileSync(resolve(ROOT, "technology-scenario-data.csv"), toCsv(technologyHeaders,
  project.technologyScenarios.map((technology) => ({
    input_sha256: inputHash,
    scenario_id: technology.id,
    scenario_title: technology.title,
    china_technology: technology.chinaTechnology,
    global_technology: technology.globalTechnology,
    china_efficiency_multiplier: technology.chinaEfficiencyMultiplier,
    global_efficiency_multiplier: technology.globalEfficiencyMultiplier,
    source_ids: technology.sourceIds.join(";")
  }))
));

const sourceHeaders = [
  "input_sha256", "source_id", "publisher", "title", "tier", "publication_date",
  "claim", "exact_locator", "verification_status", "verification_method", "verified_on",
  "independent_human_review", "url"
];
writeFileSync(resolve(auditDir, "source-verification.csv"), toCsv(sourceHeaders, project.sources.map((source) => ({
  input_sha256: inputHash,
  source_id: source.id,
  publisher: source.publisher,
  title: source.title,
  tier: source.tier,
  publication_date: source.publicationDate,
  claim: source.claim,
  exact_locator: source.locator,
  verification_status: source.verificationStatus,
  verification_method: source.verificationMethod,
  verified_on: source.verifiedOn,
  independent_human_review: source.independentHumanReview,
  url: source.url
}))));

const includedSourceIds = new Set([
  ...scenarios.flatMap((scenario) => scenario.blocks.flatMap((block) => block.sourceIds)),
  ...facilityRegister.filter((record) => record.coverageRole === "additive").flatMap((record) => record.sourceIds),
  ...benchmarks.globalBenchmark.sourceIds,
  ...benchmarks.marketForecast.sourceIds,
  ...benchmarks.countryOverrides.flatMap((record) => record.sourceIds)
]);
const includedSources = project.sources.filter((source) => includedSourceIds.has(source.id));
const report = `# Source-verification report

Input SHA-256: \`${inputHash}\`

Observation cutoff: **${project.metadata.observationCutoff}**

Research-publication cutoff: **${project.metadata.researchPublicationCutoff}**

Reproduction check: **complete**

Independent human review: **pending**

“Independent” here means the build reconstructs each displayed value from canonical inputs and checks it against a source-specific locator. It does **not** mean a second human auditor has signed off.

## Material corrections in this audit pass

- Capacity is now registered independently of price availability. The additive register contains **${round(coverage.capacityRegister.registeredCapacityMw, 1).toLocaleString()} MW** across **${coverage.capacityRegister.registeredRegionCount}** country-region keys.
- Price coverage is explicit: the combined observed-price-or-tariff category covers **${round(coverage.priceScenarios.find((row) => row.evidenceId === "comparable_proxy").registeredCapacityCoveragePct, 1)}%** of registered capacity, while the strict data-center-specific audit subset covers **${round(coverage.priceScenarios.find((row) => row.evidenceId === "data_center_tariff_evidence").registeredCapacityCoveragePct, 1)}%**.
- Ten non-overlapping JLL US market records add **27,585 MW** of year-end 2025 leased plus hyperscaler-owned capacity. The earlier CBRE Virginia and Dallas wholesale records remain as non-additive source comparisons.
- Official regional capacity for Great Britain and end-2025 live market capacity for India are in the register even where a qualifying regional price is absent.
- The country-gap queue is generated from observed country totals where available and otherwise from named-market forecast minima; it is not presented as a complete country census.
- The CAICT treemap is paired with the **10.43 million racks at 2025-03-31** denominator. The separately published June 2025 total is not mixed into the derivation.
- Hohhot / Helinger is **442.5 MW of commissioned design IT capacity**, derived from 11 × 16,091 standard racks × 2.5 kW. The reported 326 MW is an occupied facility-load cross-check, not the chart width.
- The unsupported 169 MW Guangdong regional weighting was removed. The proxy scenario applies the Pearl River Delta public tariff uniformly to the derived Guangdong capacity and labels it as a conservative proxy.
- Applicable tariffs and official industrial averages are combined in the public curves, while every block retains its evidence class and the strict data-center-specific subset remains separately quantified. Hohhot's delivered-price observation is retained only in that subset because its capacity is nested inside Inner Mongolia's provincial width.

## Included source checks (${includedSources.length})

| ID | Publisher | Status | Exact locator | Verification |
|---|---|---|---|---|
${includedSources.map((source) => `| \`${source.id}\` | ${source.publisher} | ${source.verificationStatus} | ${source.locator.replaceAll("|", "\\|")} | ${source.verificationMethod.replaceAll("|", "\\|")} |`).join("\n")}

## Full register

The machine-readable register, including excluded or only partially verified candidates, is in [source-verification.csv](source-verification.csv). Each record retains its URL, publication date, exact locator, check method, and human-review status.
`;
writeFileSync(resolve(auditDir, "verification-report.md"), report);

console.log(`Generated ${scenarios.length} curves from input ${inputHash.slice(0, 12)}…`);
console.log(`Derived ${provinces.length} provincial capacities and registered ${project.sources.length} sources.`);
